site_name: WQE
site_description: "Word-level Quality Estimation Toolkit"
copyright: "(c) 2025 Gabriele Sarti - All rights reserved."
repo_name: "gsarti/wqe"
repo_url: http://github.com/gsarti/wqe

# Set navigation here
nav:
  - Home: index.md
  - Quickstart: notebooks/quickstart.ipynb
  - API Reference:
    - Data:
      - Data Utils: api/data/utils.md
      - Tokenizer: api/data/tokenizer.md
      - WQEEntry: api/data/wqe_entry.md
      - WQEDataset: api/data/wqe_dataset.md

plugins:
  - search
  - mknotebooks
  - autorefs
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            modernize_annotations: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_signature_annotations: false
            separate_signature: true
            signature_crossrefs: true
            merge_init_into_class: true
            parameter_headings: true
            show_root_heading: false
            docstring_options:
              ignore_init_summary: true
            show_source: false
            filters:
              - "!^_"
              - "^__init__$"
              - "!^can_replace$"
              - "!^compose$"
              - "!^render$"
              - "!^render_line$"
              - "!^render_lines$"
              - "!^get_content_width$"
              - "!^get_content_height$"
              - "!^compose_add_child$"

theme:
  name: material
  custom_dir: docs/assets
  logo: assets/img/wqe_logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.footer
    - content.code.annotations
    - content.code.copy
    - announce.dismiss
    - navigation.top
    - navigation.instant
    - toc.follow
    - content.tabs.link
    - search.share
    - search.highlight
    - search.suggest
  icon:
    logo: logo
  favicon: assets/img/wqe_logo.png
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: diagram
          class: diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/object/apply:pymdownx.arithmatex.arithmatex_fenced_format {kwds: {mode: generic, tag: pre}}
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - extra
  - admonition
  - codehilite
  - markdown.extensions.attr_list
  - toc:
      baselevel: 1
      permalink: true
      toc_depth: 3
  - def_list

extra_css:
  - custom.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - custom.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gsarti/wqe
      name: WQE on Github
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/wqe
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/gsarti_
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/gsarti.com
